### ISSUE TITLE
When update to 1.20.1?

### ISSUE THREAD

**Issue by vladeron** [Zonespace27/RP-Info-Panel#1]
### Description of the feature

When update to 1.20.1?

### Why should this be added?

Because

**Comment by Zonespace27** [comment]
I can look into it, though no promise on an ETA.

**Comment by Zonespace27** [comment]
Done!
https://github.com/Zonespace27/RP-Info-Panel/releases/tag/rp-info-panel-1.20.1-v1.0.4
It should be on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/rp-info-panel) and [Modrinth](https://modrinth.com/mod/rp-info-panel) soon.
